
#\u914D\u7F6EES
spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    cache: false